# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_po_cpp <- function(beta_tilde, slambda, lambda1, lambda2, penmat, Q, eigval, fast, maxiter, rho, beta_old) {
    .Call(`_ssmurf_admm_po_cpp`, beta_tilde, slambda, lambda1, lambda2, penmat, Q, eigval, fast, maxiter, rho, beta_old)
}

admm_po_cppAdj <- function(beta_tilde, slambda, lambda1, lambda2, penmat, Q, eigval, fast, maxiter, rho, beta_old) {
    .Call(`_ssmurf_admm_po_cppAdj`, beta_tilde, slambda, lambda1, lambda2, penmat, Q, eigval, fast, maxiter, rho, beta_old)
}

XtV <- function(X, V) {
    .Call(`_ssmurf_XtV`, X, V)
}

XB <- function(X, B) {
    .Call(`_ssmurf_XB`, X, B)
}

XXt <- function(X, Xt) {
    .Call(`_ssmurf_XXt`, X, Xt)
}

